//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wiadomosci
    {
        public int Id { get; set; }
        public int Od { get; set; }
        public int Do { get; set; }
        public System.DateTime Data { get; set; }
        public string Wiadomosc { get; set; }
    }
}
